### ISSUE TITLE
Login Endpoint

### ISSUE THREAD

**Issue by theEpsilon** [AWT-SS22-Track-Trace-3/backend#10]
Endpoint to login users with a fixed ID. Registered user IDs should be persisted. There is no option to register new users via a self-service UI (i.e. user ids are hardcoded).

Required:
- [x] Endpoint to check User ID for validity
- [x] Endpoint returns Set-Cookie-Header with the user ID (or some session token) upon successful login
- [x] Cookie value (session token or user id) is checked for every future request (authentication) **(optional, might also be added later)**

**Comment by dittmanndennis** [comment]
@theEpsilon can be closed?
