### ISSUE TITLE
Make manufacturer information array and relational

### ISSUE THREAD

**Issue by theEpsilon** [AWT-SS22-Track-Trace-3/backend#15]
A product can have multiple manufacturers so manufacturer information inside a product item should look like this:

`
manufacturers: [
{
"id": "<id>"
},
{
"id": "<id>"
}
]
`

**Comment by dittmanndennis** [comment]
that should already work. the manufacterer_name or manufacturer_address is not checked for a particular type. however, I will change the names to manufacturer_names and manufacturer_addresses to imply the possibility of multiple manufacturers.
