### ISSUE TITLE
Set CORS headers

### ISSUE THREAD

**Issue by theEpsilon** [AWT-SS22-Track-Trace-3/backend#23]
Backend does not set CORS headers. Read online on how to negotiate CORS headers correctly. This issue effectively prevents the browser from accessing the backend.

**Comment by dittmanndennis** [comment]
will configure to allow port 3000 as origin

**Comment by dittmanndennis** [comment]
it is now available on branch "initial_tracing" and will be added to branch "main" with the PR #24 .

**Comment by dittmanndennis** [comment]
can this issue be closed?

**Comment by theEpsilon** [comment]
Issue does not seem to be fixed, still getting CORS errors.
