### ISSUE TITLE
Search endpoint

### ISSUE THREAD

**Issue by theEpsilon** [AWT-SS22-Track-Trace-3/backend#27]
search endpoint to return sepcific products based on search query. Search query can be assumed to already be in MongoDB format when requested.

**Comment by dittmanndennis** [comment]
for security reasons we should pre-define queries for users of access_lvl 0, 1, and 2 @theEpsilon

**Comment by theEpsilon** [comment]
Sounds like you have an idea on how to do that already. Mind to elaborate?
